$lines = Get-Content bot-manager.js -Encoding UTF8

$lines[747] = "      await this.apiCall('answerCallbackQuery', { callback_query_id: callbackQuery.id, text: lang === 'ar' ? 'تم إلغاء تثبيت الإعلان لدى الجميع.' : 'Announcement unpinned.', show_alert: true });"
$lines[1044] = "        const statsAr = ``📊 **إحصائيات البوت التفصيلية:**\n\n`` +"
$lines[1045] = "          ``👥 **المشتركون**\n`` +"
$lines[1046] = "          ``- إجمالي المشتركين: ${totalUsers}\n`` +"
$lines[1047] = "          ``- المشتركون الجدد (أسبوع): ${weeklySubscribers}\n`` +"
$lines[1048] = "          ``- المشتركون الجدد (شهر): ${monthlySubscribers}\n\n`` +"
$lines[1049] = "          ``📈 **النشاط**\n`` +"
$lines[1050] = "          ``- نشط اليوم: ${dailyActive}\n`` +"
$lines[1051] = "          ``- نشط هذا الأسبوع: ${weeklyActive}\n`` +"
$lines[1052] = "          ``- نشط هذا الشهر: ${monthlyActive}\n\n`` +"
$lines[1053] = "          ``⚡ **الوصول والأداء**\n`` +"
$lines[1054] = "          ``- نسبة الوصول (شهرياً): ${reachPercentage}%\n`` +"
$lines[1055] = "          ``- إجمالي الطلبات/النقرات: ${totalRequests}\n`` +"
$lines[1056] = "          ``- متوسط الاستجابة (ميلي ثانية): ${avgLatency}ms\n\n`` +"
$lines[1057] = "          ``📁 **المحتوى**\n`` +"
$lines[1058] = "          ``- عدد الأزرار المتاحة: ${totalButtons}\n`` +"
$lines[1059] = "          ``- عدد الملفات المرفوعة: ${totalFiles}\n`` +"
$lines[1060] = "          ``- الزر الأكثر طلباً: ${topButtonStr}\n\n`` +"
$lines[1061] = "          ``🚫 **الحظر**\n`` +"
$lines[1062] = "          ``- عدد من قام بحظر البوت: ${blockedUsers}``;"
$lines[1063] = ""

$lines[1092] = "          const cfgText = (lang === 'ar' ? 'الإعدادات\n\nالمراقبة: ' : 'Settings\n\nMonitoring: ') + monStatus;"
$lines[1214] = "            [{ text: t(lang, 'BTN_BACK') }]"
$lines[1234] = "            [{ text: t(lang, 'BTN_BACK') }]"
$lines[1265] = "        if (text !== '/skip' && text !== t(lang, 'MSG_ADMIN_35')) {"
$lines[1291] = "        state.isPinned = text === t(lang, 'MSG_ADMIN_38');"
$lines[1320] = "               const txt = ``📢 *${msgTitle}*\n\n${msgContent}\n\n${updatedAnn.is_pinned ? '📌 (Pinned)' : ''}``;"

$lines | Set-Content bot-manager.js -Encoding UTF8
